# BTC/USDT · PPO 强化学习训练

使用 Stable Baselines 3 (PPO) 对 1 分钟 K 线数据进行训练。

**观测特征**：EMA 偏差率、布林带位置、成交量比率、RSI、MACD  
**奖励函数**：步骤收益 − 回撤惩罚（兼顾收益与风险）  
**数据来源**：PostgreSQL (OHLCV) + Binance/数据库 (爆仓)

## 1. 配置

In [32]:
# ── 数据参数（与 crypto_kline_analysis 保持一致）────────────────
SYMBOL      = "BTC/USDT"
START_DATE  = "2025-10-01 00:00:00"
END_DATE    = "2026-04-13 00:00:00"
TIMEZONE    = "Asia/Shanghai"
DB_TABLE    = "public.crypto_kline_binance"
ONLY_CLOSED = True

# ── RL 超参数 ────────────────────────────────────────────────────
WINDOW_SIZE     = 30        # 滑动观测窗口（分钟数）
INITIAL_BALANCE = 10_000.0  # 初始资金（USD）
COMMISSION      = 0.001     # 单向手续费率
PENALTY_WEIGHT  = 0.05      # 回撤惩罚系数（越大越厌恶风险）
TRAIN_RATIO     = 0.8       # 训练集比例

# ── PPO 超参数 ───────────────────────────────────────────────────
TOTAL_TIMESTEPS = 1_000_000
PPO_KWARGS = dict(
    learning_rate = 3e-4,
    n_steps       = 2048,
    batch_size    = 64,
    n_epochs      = 10,
    gamma         = 0.99,
    gae_lambda    = 0.95,
    clip_range    = 0.2,
    ent_coef      = 0.005,
    vf_coef       = 0.5,
    max_grad_norm = 0.5,
)
RUN_NAME   = f"{SYMBOL.replace('/','')}__ppo"
MODEL_DIR  = "../models/saved"
LOG_DIR    = "../models/logs"
# ────────────────────────────────────────────────────────────────

## 2. 数据加载与特征工程

### 2.1 OHLCV 加载

In [33]:
import sys
sys.path.insert(0, "..")

import numpy as np
from tqdm.notebook import tqdm
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
matplotlib.rcParams['font.sans-serif'] = ['Noto Sans CJK JP', 'DejaVu Sans']
matplotlib.rcParams['axes.unicode_minus'] = False
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import EvalCallback, CheckpointCallback
from stable_baselines3.common.vec_env import DummyVecEnv
import gymnasium as gym
from gymnasium import spaces
from pathlib import Path

from utils.db import read_ohlcv

tz = TIMEZONE
start_utc = pd.Timestamp(START_DATE, tz=tz).tz_convert("UTC").isoformat()
end_utc   = pd.Timestamp(END_DATE,   tz=tz).tz_convert("UTC").isoformat()

df_raw = read_ohlcv(SYMBOL, start=start_utc, end=end_utc,
                    table=DB_TABLE, only_closed=ONLY_CLOSED)
ts = df_raw["timestamp"]
if ts.dt.tz is None:
    ts = ts.dt.tz_localize("UTC")
df_raw["timestamp"] = ts.dt.tz_convert(tz)

print(f"OHLCV 行数  : {len(df_raw)}")
print(f"时间范围    : {df_raw['timestamp'].min()} → {df_raw['timestamp'].max()}")
df_raw.head(3)

/home/davidlyu/projects/GinkgoBrain/.venv/lib/python3.12/site-packages/rich/live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

OHLCV 行数  : 279360

时间范围    : 2025-10-01 00:00:00+08:00 → 2026-04-12 23:59:00+08:00

,timestamp,open,high,low,close,volume
0,2025-10-01 00:00:00+08:00,113106.15,113115.97,113073.04,113074.30,4.83614
1,2025-10-01 00:01:00+08:00,113074.31,113156.00,113055.28,113156.00,5.57704
2,2025-10-01 00:02:00+08:00,113156.00,113156.00,113125.64,113136.92,1.58706

### 2.2 指标计算与特征合并

In [34]:
d = df_raw.copy()

# ── EMA ──────────────────────────────────────────────────────────
d["ema9"]  = d["close"].ewm(span=9,  adjust=False).mean()
d["ema21"] = d["close"].ewm(span=21, adjust=False).mean()
d["ema55"] = d["close"].ewm(span=55, adjust=False).mean()

# ── Bollinger Band (20, 2σ) ───────────────────────────────────────
d["bb_mid"]   = d["close"].rolling(20).mean()
d["bb_std"]   = d["close"].rolling(20).std()
d["bb_upper"] = d["bb_mid"] + 2 * d["bb_std"]
d["bb_lower"] = d["bb_mid"] - 2 * d["bb_std"]

# ── RSI (14) ─────────────────────────────────────────────────────
delta = d["close"].diff()
d["rsi"] = 100 - 100 / (1 + delta.clip(lower=0).rolling(14).mean()
                           / (-delta.clip(upper=0)).rolling(14).mean().replace(0, np.nan))

# ── MACD (12, 26, 9) ─────────────────────────────────────────────
ema12 = d["close"].ewm(span=12, adjust=False).mean()
ema26 = d["close"].ewm(span=26, adjust=False).mean()
d["macd"]        = ema12 - ema26
d["macd_signal"] = d["macd"].ewm(span=9, adjust=False).mean()
d["macd_hist"]   = d["macd"] - d["macd_signal"]

# ── 成交量均线 ────────────────────────────────────────────────────
d["vol_ma20"] = d["volume"].rolling(20).mean()

d = d.dropna().reset_index(drop=True)
print(f"有效行数: {len(d)}")
d.head(3)

/home/davidlyu/projects/GinkgoBrain/.venv/lib/python3.12/site-packages/rich/live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

/home/davidlyu/projects/GinkgoBrain/.venv/lib/python3.12/site-packages/rich/live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

有效行数: 279313

,timestamp,open,high,low,close,volume,ema9,ema21,ema55,bb_mid,bb_std,bb_upper,bb_lower,rsi,macd,macd_signal,macd_hist,vol_ma20
0,2025-10-01 00:19:00+08:00,113085.45,113131.97,113085.45,113122.59,7.62101,113084.267918,113089.110554,113086.860705,113103.4555,44.298862,113192.053223,113014.857777,47.326260,-3.675359,-1.987165,-1.688194,6.456830
1,2025-10-01 00:20:00+08:00,113122.59,113154.71,113038.55,113100.48,7.78331,113087.510334,113090.144140,113087.347108,113104.7645,43.775705,113192.315910,113017.213090,43.134980,-2.233988,-2.036530,-0.197459,6.604188
2,2025-10-01 00:21:00+08:00,113100.48,113279.92,113100.48,113279.91,26.66259,113125.990268,113107.395582,113094.224355,113110.9600,57.898786,113226.757573,112995.162427,59.146992,13.234253,1.017627,12.216626,7.658466

### 2.3 归一化特征矩阵

In [35]:
# 每个时间步的特征向量（11维，窗口化后作为观测输入）
feat = d.copy()

feat["ret_1m"]       = feat["close"].pct_change().fillna(0).clip(-0.1, 0.1)
feat["hl_ratio"]     = (feat["high"] - feat["low"]) / (feat["close"] + 1e-8)
feat["body_ratio"]   = (feat["close"] - feat["open"]) / (feat["high"] - feat["low"] + 1e-8)
feat["ema9_r"]       = (feat["ema9"]  - feat["close"]) / (feat["close"] + 1e-8)
feat["ema21_r"]      = (feat["ema21"] - feat["close"]) / (feat["close"] + 1e-8)
feat["ema55_r"]      = (feat["ema55"] - feat["close"]) / (feat["close"] + 1e-8)
feat["bb_pos"]       = ((feat["close"] - feat["bb_lower"])
                        / (feat["bb_upper"] - feat["bb_lower"] + 1e-8)).clip(0, 2)
feat["vol_ratio"]    = np.log1p(feat["volume"] / (feat["vol_ma20"] + 1e-8))
feat["rsi_norm"]     = feat["rsi"] / 100
feat["macd_norm"]    = feat["macd"] / (feat["close"] + 1e-8)
feat["macd_hist_norm"]= feat["macd_hist"] / (feat["close"] + 1e-8)

FEATURE_COLS = [
    "ret_1m", "hl_ratio", "body_ratio",
    "ema9_r", "ema21_r", "ema55_r", "bb_pos",
    "vol_ratio",
    "rsi_norm", "macd_norm", "macd_hist_norm",
]

feat_matrix = feat[FEATURE_COLS].ffill().fillna(0).values.astype(np.float32)
close_arr   = feat["close"].values.astype(np.float32)

print(f"特征矩阵形状 : {feat_matrix.shape}  ({len(FEATURE_COLS)} 维 × {len(feat)} 步)")
print(f"特征列       : {FEATURE_COLS}")

/home/davidlyu/projects/GinkgoBrain/.venv/lib/python3.12/site-packages/rich/live.py:260: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

特征矩阵形状 : (279313, 11)  (11 维 × 279313 步)

特征列       : ['ret_1m', 'hl_ratio', 'body_ratio', 'ema9_r', 'ema21_r', 'ema55_r', 'bb_pos', 'vol_ratio',
'rsi_norm', 'macd_norm', 'macd_hist_norm']

## 3. 自定义交易环境

**观测空间**：`(WINDOW_SIZE × 11 + 2,)` 展平向量  
— 最近 `WINDOW_SIZE` 步的归一化特征 + `[balance_ratio, holding_ratio]` 组合状态

**动作空间**：Discrete(3) — 0=持仓, 1=全仓买入, 2=全仓卖出

**奖励函数**：  
`reward = step_return − PENALTY_WEIGHT × current_drawdown`  
— 步骤收益驱动盈利，回撤惩罚抑制风险

In [36]:
class CryptoPPOEnv(gym.Env):
    """
    1-minute crypto trading environment for SB3 PPO.

    Observation = flatten(features[t-W:t])  +  [balance_ratio, holding_ratio]
    Reward      = step_return  -  penalty_weight * drawdown
    """
    metadata = {"render_modes": []}

    def __init__(
        self,
        features: np.ndarray,   # (T, n_feat)  pre-normalised
        prices:   np.ndarray,   # (T,)  close prices for execution
        window_size:     int   = WINDOW_SIZE,
        initial_balance: float = INITIAL_BALANCE,
        commission:      float = COMMISSION,
        penalty_weight:  float = PENALTY_WEIGHT,
    ):
        super().__init__()
        self.features        = features
        self.prices          = prices
        self.window_size     = window_size
        self.initial_balance = initial_balance
        self.commission      = commission
        self.penalty_weight  = penalty_weight
        self.n_feat          = features.shape[1]

        n_obs = window_size * self.n_feat + 2
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(n_obs,), dtype=np.float32
        )
        self.action_space = spaces.Discrete(3)  # 0=hold 1=buy 2=sell
        self._reset_state()

    # ── internal helpers ────────────────────────────────────────
    def _reset_state(self):
        self.balance    = self.initial_balance
        self.position   = 0.0
        self.peak_value = self.initial_balance
        self.step_idx   = self.window_size
        self.trades: list[dict] = []
        self.portfolio_history: list[float] = []

    def _portfolio_value(self, price: float) -> float:
        return self.balance + self.position * price

    def _get_obs(self) -> np.ndarray:
        window = self.features[self.step_idx - self.window_size : self.step_idx]
        price  = float(self.prices[self.step_idx])
        pv     = self._portfolio_value(price)
        port   = np.array([
            self.balance / self.initial_balance,
            self.position * price / self.initial_balance,
        ], dtype=np.float32)
        return np.concatenate([window.flatten(), port])

    # ── gym API ─────────────────────────────────────────────────
    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed)
        self._reset_state()
        return self._get_obs(), {}

    def step(self, action: int):
        price      = float(self.prices[self.step_idx])
        prev_value = self._portfolio_value(price)

        # ── execute action ───────────────────────────────────────
        if action == 1 and self.balance > 0:          # buy
            qty = self.balance * (1 - self.commission) / price
            self.position += qty
            self.balance   = 0.0
            self.trades.append({"step": self.step_idx, "side": "buy",  "price": price})
        elif action == 2 and self.position > 0:       # sell
            self.balance  += self.position * price * (1 - self.commission)
            self.position  = 0.0
            self.trades.append({"step": self.step_idx, "side": "sell", "price": price})

        self.step_idx += 1
        done = self.step_idx >= len(self.prices) - 1

        new_price = float(self.prices[self.step_idx])
        new_value = self._portfolio_value(new_price)
        self.portfolio_history.append(new_value)

        # ── reward = step return − drawdown penalty ──────────────
        step_ret = (new_value - prev_value) / (prev_value + 1e-8)
        if new_value > self.peak_value:
            self.peak_value = new_value
        drawdown = (self.peak_value - new_value) / (self.peak_value + 1e-8)
        reward   = float(step_ret - self.penalty_weight * drawdown)

        obs  = self._get_obs()
        info = {
            "portfolio_value": new_value,
            "balance":         self.balance,
            "position":        self.position,
            "drawdown":        drawdown,
            "n_trades":        len(self.trades),
        }
        return obs, reward, done, False, info

    def render(self):
        price = float(self.prices[self.step_idx])
        pv    = self._portfolio_value(price)
        dd    = (self.peak_value - pv) / (self.peak_value + 1e-8)
        print(f"step={self.step_idx:5d} | PV={pv:,.2f} | DD={dd:.2%} | trades={len(self.trades)}")

## 4. 数据集划分（8:2）

In [37]:
n_total = len(feat_matrix)
n_train = int(n_total * TRAIN_RATIO)
n_eval  = n_total - n_train

train_feat, eval_feat   = feat_matrix[:n_train], feat_matrix[n_train:]
train_price, eval_price = close_arr[:n_train],   close_arr[n_train:]
train_time  = feat["timestamp"].iloc[:n_train]
eval_time   = feat["timestamp"].iloc[n_train:]

print(f"总步数  : {n_total}")
print(f"训练集  : {n_train} 步  ({train_time.iloc[0]}  →  {train_time.iloc[-1]})")
print(f"验证集  : {n_eval} 步  ({eval_time.iloc[0]}  →  {eval_time.iloc[-1]})")

# 可行性检查：窗口必须 < 训练集长度
assert n_train > WINDOW_SIZE and n_eval > WINDOW_SIZE, \
    f"数据集太短，请缩小 WINDOW_SIZE 或扩大日期范围"
print("✓ 数据集检查通过")

总步数  : 279313

训练集  : 223450 步  (2025-10-01 00:19:00+08:00  →  2026-03-05 04:55:00+08:00)

验证集  : 55863 步  (2026-03-05 04:56:00+08:00  →  2026-04-12 23:59:00+08:00)

✓ 数据集检查通过

## 5. SB3 PPO 训练

奖励指标同时考虑：
- **收益**：`step_return = ΔPV / PV`
- **风险**：`−PENALTY_WEIGHT × drawdown`（当前回撤越大惩罚越重）

In [38]:
from pathlib import Path

Path(MODEL_DIR).mkdir(parents=True, exist_ok=True)
Path(LOG_DIR).mkdir(parents=True, exist_ok=True)

def make_train_env():
    env = CryptoPPOEnv(train_feat, train_price)
    return Monitor(env)

def make_eval_env():
    env = CryptoPPOEnv(eval_feat, eval_price)
    return Monitor(env)

train_vec = DummyVecEnv([make_train_env])
eval_vec  = DummyVecEnv([make_eval_env])

callbacks = [
    EvalCallback(
        eval_vec,
        best_model_save_path=f"{MODEL_DIR}/{RUN_NAME}",
        log_path=f"{LOG_DIR}/{RUN_NAME}",
        eval_freq=10_000,
        n_eval_episodes=1,
        deterministic=True,
        render=False,
        verbose=1,
    ),
    CheckpointCallback(
        save_freq=50_000,
        save_path=f"{MODEL_DIR}/{RUN_NAME}/checkpoints",
        name_prefix=RUN_NAME,
    ),
]

model = PPO(
    "MlpPolicy",
    train_vec,
    tensorboard_log=LOG_DIR,
    verbose=1,
    **PPO_KWARGS,
)

print(f"观测维度   : {model.observation_space.shape}")
print(f"训练步数   : {TOTAL_TIMESTEPS:,}")
print(f"TensorBoard: tensorboard --logdir {LOG_DIR}")

Using cuda device

/home/davidlyu/projects/GinkgoBrain/.venv/lib/python3.12/site-packages/stable_baselines3/common/on_policy_algorithm
.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not
using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See
https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export
CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and
the training might take longer than on CPU.
  warnings.warn(

观测维度   : (332,)

训练步数   : 1,000,000

TensorBoard: tensorboard --logdir ../models/logs

In [ ]:
model.learn(
    total_timesteps=TOTAL_TIMESTEPS,
    callback=callbacks,
    tb_log_name=RUN_NAME,
    progress_bar=True,
)
model.save(f"{MODEL_DIR}/{RUN_NAME}/final")
print(f"模型已保存至 {MODEL_DIR}/{RUN_NAME}/final.zip")

Logging to ../models/logs/BTCUSDT__ppo_4

-----------------------------
| time/              |      |
|    fps             | 935  |
|    iterations      | 1    |
|    time_elapsed    | 2    |
|    total_timesteps | 2048 |
-----------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 736         |
|    iterations           | 2           |
|    time_elapsed         | 5           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.010769395 |
|    clip_fraction        | 0.0731      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.09       |
|    explained_variance   | -3.56       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00553    |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0137     |
|    value_loss           | 0.0292      |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 683         |
|    iterations           | 3           |
|    time_elapsed         | 8           |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.007744298 |
|    clip_fraction        | 0.0993      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.08       |
|    explained_variance   | -0.784      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00157    |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0135     |
|    value_loss           | 0.0105      |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 657         |
|    iterations           | 4           |
|    time_elapsed         | 12          |
|    total_timesteps      | 8192        |
| train/                  |             |
|    approx_kl            | 0.010358763 |
|    clip_fraction        | 0.0841      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.07       |
|    explained_variance   | -0.918      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0409     |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0165     |
|    value_loss           | 0.00779     |
-----------------------------------------

Eval num_timesteps=10000, episode_reward=-2664.00 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -2.66e+03   |
| time/                   |             |
|    total_timesteps      | 10000       |
| train/                  |             |
|    approx_kl            | 0.010263588 |
|    clip_fraction        | 0.0955      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.06       |
|    explained_variance   | -0.982      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0171     |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0153     |
|    value_loss           | 0.00605     |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 217   |
|    iterations      | 5     |
|    time_elapsed    | 47    |
|    total_timesteps | 10240 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 243         |
|    iterations           | 6           |
|    time_elapsed         | 50          |
|    total_timesteps      | 12288       |
| train/                  |             |
|    approx_kl            | 0.011549467 |
|    clip_fraction        | 0.0903      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.06       |
|    explained_variance   | -0.43       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.027      |
|    n_updates            | 50          |
|    policy_gradient_loss | -0.0171     |
|    value_loss           | 0.00479     |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 266         |
|    iterations           | 7           |
|    time_elapsed         | 53          |
|    total_timesteps      | 14336       |
| train/                  |             |
|    approx_kl            | 0.008936045 |
|    clip_fraction        | 0.0805      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.05       |
|    explained_variance   | -0.945      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0506     |
|    n_updates            | 60          |
|    policy_gradient_loss | -0.0148     |
|    value_loss           | 0.00384     |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 287        |
|    iterations           | 8          |
|    time_elapsed         | 56         |
|    total_timesteps      | 16384      |
| train/                  |            |
|    approx_kl            | 0.00846054 |
|    clip_fraction        | 0.0854     |
|    clip_range           | 0.2        |
|    entropy_loss         | -1.04      |
|    explained_variance   | -1.09      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0492    |
|    n_updates            | 70         |
|    policy_gradient_loss | -0.0159    |
|    value_loss           | 0.0027     |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 306         |
|    iterations           | 9           |
|    time_elapsed         | 60          |
|    total_timesteps      | 18432       |
| train/                  |             |
|    approx_kl            | 0.009423336 |
|    clip_fraction        | 0.0851      |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.04       |
|    explained_variance   | -0.582      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0313     |
|    n_updates            | 80          |
|    policy_gradient_loss | -0.0148     |
|    value_loss           | 0.00204     |
-----------------------------------------

Eval num_timesteps=20000, episode_reward=-2598.38 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -2.6e+03    |
| time/                   |             |
|    total_timesteps      | 20000       |
| train/                  |             |
|    approx_kl            | 0.011087742 |
|    clip_fraction        | 0.112       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.02       |
|    explained_variance   | -0.629      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0287     |
|    n_updates            | 90          |
|    policy_gradient_loss | -0.0174     |
|    value_loss           | 0.0014      |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 217   |
|    iterations      | 10    |
|    time_elapsed    | 94    |
|    total_timesteps | 20480 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 231         |
|    iterations           | 11          |
|    time_elapsed         | 97          |
|    total_timesteps      | 22528       |
| train/                  |             |
|    approx_kl            | 0.008912628 |
|    clip_fraction        | 0.072       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.02       |
|    explained_variance   | -0.376      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0284     |
|    n_updates            | 100         |
|    policy_gradient_loss | -0.0147     |
|    value_loss           | 0.000952    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 244         |
|    iterations           | 12          |
|    time_elapsed         | 100         |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.010769562 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.01       |
|    explained_variance   | -0.889      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0121     |
|    n_updates            | 110         |
|    policy_gradient_loss | -0.0172     |
|    value_loss           | 0.000756    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 256         |
|    iterations           | 13          |
|    time_elapsed         | 103         |
|    total_timesteps      | 26624       |
| train/                  |             |
|    approx_kl            | 0.010637693 |
|    clip_fraction        | 0.109       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1          |
|    explained_variance   | -0.89       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0242     |
|    n_updates            | 120         |
|    policy_gradient_loss | -0.0164     |
|    value_loss           | 0.000524    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 267         |
|    iterations           | 14          |
|    time_elapsed         | 107         |
|    total_timesteps      | 28672       |
| train/                  |             |
|    approx_kl            | 0.009717093 |
|    clip_fraction        | 0.113       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.986      |
|    explained_variance   | -1.74       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00376    |
|    n_updates            | 130         |
|    policy_gradient_loss | -0.0196     |
|    value_loss           | 0.000391    |
-----------------------------------------

Eval num_timesteps=30000, episode_reward=-2513.96 +/- 0.00

Episode length: 55832.00 +/- 0.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 5.58e+04     |
|    mean_reward          | -2.51e+03    |
| time/                   |              |
|    total_timesteps      | 30000        |
| train/                  |              |
|    approx_kl            | 0.0110053625 |
|    clip_fraction        | 0.127        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.974       |
|    explained_variance   | -1.28        |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0394      |
|    n_updates            | 140          |
|    policy_gradient_loss | -0.0198      |
|    value_loss           | 0.000301     |
------------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 216   |
|    iterations      | 15    |
|    time_elapsed    | 141   |
|    total_timesteps | 30720 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 225         |
|    iterations           | 16          |
|    time_elapsed         | 145         |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.012505969 |
|    clip_fraction        | 0.129       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.956      |
|    explained_variance   | -1.74       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0368     |
|    n_updates            | 150         |
|    policy_gradient_loss | -0.0222     |
|    value_loss           | 0.000211    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 233         |
|    iterations           | 17          |
|    time_elapsed         | 148         |
|    total_timesteps      | 34816       |
| train/                  |             |
|    approx_kl            | 0.010608191 |
|    clip_fraction        | 0.111       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.934      |
|    explained_variance   | -1.72       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0168     |
|    n_updates            | 160         |
|    policy_gradient_loss | -0.019      |
|    value_loss           | 0.000149    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 241         |
|    iterations           | 18          |
|    time_elapsed         | 152         |
|    total_timesteps      | 36864       |
| train/                  |             |
|    approx_kl            | 0.010356868 |
|    clip_fraction        | 0.11        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.914      |
|    explained_variance   | -1.73       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0246     |
|    n_updates            | 170         |
|    policy_gradient_loss | -0.0194     |
|    value_loss           | 0.000112    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 249         |
|    iterations           | 19          |
|    time_elapsed         | 155         |
|    total_timesteps      | 38912       |
| train/                  |             |
|    approx_kl            | 0.013522148 |
|    clip_fraction        | 0.123       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.885      |
|    explained_variance   | -3.68       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0247     |
|    n_updates            | 180         |
|    policy_gradient_loss | -0.0213     |
|    value_loss           | 0.000106    |
-----------------------------------------

Eval num_timesteps=40000, episode_reward=-2474.39 +/- 0.00

Episode length: 55832.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 5.58e+04   |
|    mean_reward          | -2.47e+03  |
| time/                   |            |
|    total_timesteps      | 40000      |
| train/                  |            |
|    approx_kl            | 0.00980717 |
|    clip_fraction        | 0.0975     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.881     |
|    explained_variance   | -2.63      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0329    |
|    n_updates            | 190        |
|    policy_gradient_loss | -0.0173    |
|    value_loss           | 6.63e-05   |
----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 215   |
|    iterations      | 20    |
|    time_elapsed    | 190   |
|    total_timesteps | 40960 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 222         |
|    iterations           | 21          |
|    time_elapsed         | 193         |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.011400934 |
|    clip_fraction        | 0.108       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.861      |
|    explained_variance   | -2.02       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0224     |
|    n_updates            | 200         |
|    policy_gradient_loss | -0.0179     |
|    value_loss           | 5.27e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 229         |
|    iterations           | 22          |
|    time_elapsed         | 196         |
|    total_timesteps      | 45056       |
| train/                  |             |
|    approx_kl            | 0.010906834 |
|    clip_fraction        | 0.123       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.835      |
|    explained_variance   | -2.05       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0242     |
|    n_updates            | 210         |
|    policy_gradient_loss | -0.0193     |
|    value_loss           | 4.23e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 236         |
|    iterations           | 23          |
|    time_elapsed         | 199         |
|    total_timesteps      | 47104       |
| train/                  |             |
|    approx_kl            | 0.010196218 |
|    clip_fraction        | 0.098       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.812      |
|    explained_variance   | -1.35       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0145     |
|    n_updates            | 220         |
|    policy_gradient_loss | -0.0166     |
|    value_loss           | 2.98e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 242         |
|    iterations           | 24          |
|    time_elapsed         | 202         |
|    total_timesteps      | 49152       |
| train/                  |             |
|    approx_kl            | 0.009632904 |
|    clip_fraction        | 0.0904      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.78       |
|    explained_variance   | -5.19       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0282     |
|    n_updates            | 230         |
|    policy_gradient_loss | -0.018      |
|    value_loss           | 3.75e-05    |
-----------------------------------------

Eval num_timesteps=50000, episode_reward=-2238.31 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -2.24e+03   |
| time/                   |             |
|    total_timesteps      | 50000       |
| train/                  |             |
|    approx_kl            | 0.011325164 |
|    clip_fraction        | 0.14        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.759      |
|    explained_variance   | -1.9        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0172     |
|    n_updates            | 240         |
|    policy_gradient_loss | -0.0195     |
|    value_loss           | 2.21e-05    |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 216   |
|    iterations      | 25    |
|    time_elapsed    | 236   |
|    total_timesteps | 51200 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 222         |
|    iterations           | 26          |
|    time_elapsed         | 239         |
|    total_timesteps      | 53248       |
| train/                  |             |
|    approx_kl            | 0.008534435 |
|    clip_fraction        | 0.0777      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.773      |
|    explained_variance   | -0.752      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0188     |
|    n_updates            | 250         |
|    policy_gradient_loss | -0.0137     |
|    value_loss           | 1.89e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 227         |
|    iterations           | 27          |
|    time_elapsed         | 242         |
|    total_timesteps      | 55296       |
| train/                  |             |
|    approx_kl            | 0.011055561 |
|    clip_fraction        | 0.114       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.743      |
|    explained_variance   | -1.25       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.00272     |
|    n_updates            | 260         |
|    policy_gradient_loss | -0.0169     |
|    value_loss           | 1.51e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 233         |
|    iterations           | 28          |
|    time_elapsed         | 245         |
|    total_timesteps      | 57344       |
| train/                  |             |
|    approx_kl            | 0.013305802 |
|    clip_fraction        | 0.13        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | -1.43       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00414    |
|    n_updates            | 270         |
|    policy_gradient_loss | -0.0198     |
|    value_loss           | 1.53e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 238         |
|    iterations           | 29          |
|    time_elapsed         | 248         |
|    total_timesteps      | 59392       |
| train/                  |             |
|    approx_kl            | 0.009105865 |
|    clip_fraction        | 0.0864      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.631      |
|    explained_variance   | -3.11       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0235     |
|    n_updates            | 280         |
|    policy_gradient_loss | -0.0164     |
|    value_loss           | 1.13e-05    |
-----------------------------------------

Eval num_timesteps=60000, episode_reward=-1850.85 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.85e+03   |
| time/                   |             |
|    total_timesteps      | 60000       |
| train/                  |             |
|    approx_kl            | 0.007980885 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.62       |
|    explained_variance   | -1.24       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0181     |
|    n_updates            | 290         |
|    policy_gradient_loss | -0.0184     |
|    value_loss           | 1.07e-05    |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 217   |
|    iterations      | 30    |
|    time_elapsed    | 282   |
|    total_timesteps | 61440 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 222         |
|    iterations           | 31          |
|    time_elapsed         | 285         |
|    total_timesteps      | 63488       |
| train/                  |             |
|    approx_kl            | 0.008750616 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.601      |
|    explained_variance   | -0.897      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0226     |
|    n_updates            | 300         |
|    policy_gradient_loss | -0.016      |
|    value_loss           | 9.74e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 226         |
|    iterations           | 32          |
|    time_elapsed         | 288         |
|    total_timesteps      | 65536       |
| train/                  |             |
|    approx_kl            | 0.009734839 |
|    clip_fraction        | 0.0908      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.584      |
|    explained_variance   | -0.476      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0339     |
|    n_updates            | 310         |
|    policy_gradient_loss | -0.0174     |
|    value_loss           | 1.21e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 231         |
|    iterations           | 33          |
|    time_elapsed         | 292         |
|    total_timesteps      | 67584       |
| train/                  |             |
|    approx_kl            | 0.009740694 |
|    clip_fraction        | 0.0771      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.553      |
|    explained_variance   | -0.279      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0282     |
|    n_updates            | 320         |
|    policy_gradient_loss | -0.0151     |
|    value_loss           | 1.36e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 235         |
|    iterations           | 34          |
|    time_elapsed         | 295         |
|    total_timesteps      | 69632       |
| train/                  |             |
|    approx_kl            | 0.008637622 |
|    clip_fraction        | 0.094       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.568      |
|    explained_variance   | -1.17       |
|    learning_rate        | 0.0003      |
|    loss                 | 0.00313     |
|    n_updates            | 330         |
|    policy_gradient_loss | -0.0192     |
|    value_loss           | 7.16e-06    |
-----------------------------------------

Eval num_timesteps=70000, episode_reward=-1775.33 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.78e+03   |
| time/                   |             |
|    total_timesteps      | 70000       |
| train/                  |             |
|    approx_kl            | 0.010672267 |
|    clip_fraction        | 0.0781      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.565      |
|    explained_variance   | -0.532      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0441     |
|    n_updates            | 340         |
|    policy_gradient_loss | -0.0141     |
|    value_loss           | 9.55e-06    |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 218   |
|    iterations      | 35    |
|    time_elapsed    | 328   |
|    total_timesteps | 71680 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 221         |
|    iterations           | 36          |
|    time_elapsed         | 332         |
|    total_timesteps      | 73728       |
| train/                  |             |
|    approx_kl            | 0.009240169 |
|    clip_fraction        | 0.0809      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.582      |
|    explained_variance   | -0.273      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00984    |
|    n_updates            | 350         |
|    policy_gradient_loss | -0.0168     |
|    value_loss           | 1.02e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 225         |
|    iterations           | 37          |
|    time_elapsed         | 335         |
|    total_timesteps      | 75776       |
| train/                  |             |
|    approx_kl            | 0.009194149 |
|    clip_fraction        | 0.0848      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.575      |
|    explained_variance   | -0.213      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0324     |
|    n_updates            | 360         |
|    policy_gradient_loss | -0.0133     |
|    value_loss           | 1.34e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 229         |
|    iterations           | 38          |
|    time_elapsed         | 339         |
|    total_timesteps      | 77824       |
| train/                  |             |
|    approx_kl            | 0.010304197 |
|    clip_fraction        | 0.0953      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.548      |
|    explained_variance   | -0.0197     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0335     |
|    n_updates            | 370         |
|    policy_gradient_loss | -0.014      |
|    value_loss           | 1.81e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 232         |
|    iterations           | 39          |
|    time_elapsed         | 343         |
|    total_timesteps      | 79872       |
| train/                  |             |
|    approx_kl            | 0.008490515 |
|    clip_fraction        | 0.089       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.507      |
|    explained_variance   | -0.376      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00758    |
|    n_updates            | 380         |
|    policy_gradient_loss | -0.0158     |
|    value_loss           | 7.97e-06    |
-----------------------------------------

Eval num_timesteps=80000, episode_reward=-1540.29 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.54e+03   |
| time/                   |             |
|    total_timesteps      | 80000       |
| train/                  |             |
|    approx_kl            | 0.010064975 |
|    clip_fraction        | 0.0934      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.483      |
|    explained_variance   | -0.266      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0323     |
|    n_updates            | 390         |
|    policy_gradient_loss | -0.0167     |
|    value_loss           | 1.15e-05    |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 216   |
|    iterations      | 40    |
|    time_elapsed    | 377   |
|    total_timesteps | 81920 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 220         |
|    iterations           | 41          |
|    time_elapsed         | 381         |
|    total_timesteps      | 83968       |
| train/                  |             |
|    approx_kl            | 0.009535719 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.49       |
|    explained_variance   | -0.455      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.017      |
|    n_updates            | 400         |
|    policy_gradient_loss | -0.0148     |
|    value_loss           | 7.62e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 223         |
|    iterations           | 42          |
|    time_elapsed         | 384         |
|    total_timesteps      | 86016       |
| train/                  |             |
|    approx_kl            | 0.008120099 |
|    clip_fraction        | 0.101       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.454      |
|    explained_variance   | -0.318      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0369     |
|    n_updates            | 410         |
|    policy_gradient_loss | -0.0162     |
|    value_loss           | 8.66e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 226         |
|    iterations           | 43          |
|    time_elapsed         | 388         |
|    total_timesteps      | 88064       |
| train/                  |             |
|    approx_kl            | 0.007948882 |
|    clip_fraction        | 0.0823      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.485      |
|    explained_variance   | -0.81       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0304     |
|    n_updates            | 420         |
|    policy_gradient_loss | -0.0149     |
|    value_loss           | 6.65e-06    |
-----------------------------------------

Eval num_timesteps=90000, episode_reward=-1385.31 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.39e+03   |
| time/                   |             |
|    total_timesteps      | 90000       |
| train/                  |             |
|    approx_kl            | 0.010191347 |
|    clip_fraction        | 0.0887      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.466      |
|    explained_variance   | -1.23       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0364     |
|    n_updates            | 430         |
|    policy_gradient_loss | -0.0178     |
|    value_loss           | 5.96e-06    |
-----------------------------------------

New best mean reward!

------------------------------
| time/              |       |
|    fps             | 213   |
|    iterations      | 44    |
|    time_elapsed    | 422   |
|    total_timesteps | 90112 |
------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 45          |
|    time_elapsed         | 426         |
|    total_timesteps      | 92160       |
| train/                  |             |
|    approx_kl            | 0.009812507 |
|    clip_fraction        | 0.0859      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.455      |
|    explained_variance   | -0.196      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0321     |
|    n_updates            | 440         |
|    policy_gradient_loss | -0.0155     |
|    value_loss           | 8.83e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 46          |
|    time_elapsed         | 429         |
|    total_timesteps      | 94208       |
| train/                  |             |
|    approx_kl            | 0.009169938 |
|    clip_fraction        | 0.0895      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.461      |
|    explained_variance   | -0.0279     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0136     |
|    n_updates            | 450         |
|    policy_gradient_loss | -0.0132     |
|    value_loss           | 9.95e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 222         |
|    iterations           | 47          |
|    time_elapsed         | 433         |
|    total_timesteps      | 96256       |
| train/                  |             |
|    approx_kl            | 0.010155614 |
|    clip_fraction        | 0.0926      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.445      |
|    explained_variance   | -0.277      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0188     |
|    n_updates            | 460         |
|    policy_gradient_loss | -0.0169     |
|    value_loss           | 6.63e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 225         |
|    iterations           | 48          |
|    time_elapsed         | 436         |
|    total_timesteps      | 98304       |
| train/                  |             |
|    approx_kl            | 0.011915464 |
|    clip_fraction        | 0.106       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.439      |
|    explained_variance   | -0.306      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0324     |
|    n_updates            | 470         |
|    policy_gradient_loss | -0.0163     |
|    value_loss           | 6.05e-06    |
-----------------------------------------

Eval num_timesteps=100000, episode_reward=-1332.40 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.33e+03   |
| time/                   |             |
|    total_timesteps      | 100000      |
| train/                  |             |
|    approx_kl            | 0.008608718 |
|    clip_fraction        | 0.0806      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.407      |
|    explained_variance   | -0.628      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0187     |
|    n_updates            | 480         |
|    policy_gradient_loss | -0.0148     |
|    value_loss           | 8.57e-06    |
-----------------------------------------

New best mean reward!

-------------------------------
| time/              |        |
|    fps             | 213    |
|    iterations      | 49     |
|    time_elapsed    | 470    |
|    total_timesteps | 100352 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 50          |
|    time_elapsed         | 473         |
|    total_timesteps      | 102400      |
| train/                  |             |
|    approx_kl            | 0.009487723 |
|    clip_fraction        | 0.0979      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.44       |
|    explained_variance   | -0.264      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0265     |
|    n_updates            | 490         |
|    policy_gradient_loss | -0.0141     |
|    value_loss           | 6.02e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 51          |
|    time_elapsed         | 476         |
|    total_timesteps      | 104448      |
| train/                  |             |
|    approx_kl            | 0.006305329 |
|    clip_fraction        | 0.0716      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.424      |
|    explained_variance   | -0.0605     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0124     |
|    n_updates            | 500         |
|    policy_gradient_loss | -0.0102     |
|    value_loss           | 9.29e-06    |
-----------------------------------------

------------------------------------------
| time/                   |              |
|    fps                  | 221          |
|    iterations           | 52           |
|    time_elapsed         | 479          |
|    total_timesteps      | 106496       |
| train/                  |              |
|    approx_kl            | 0.0076746275 |
|    clip_fraction        | 0.0831       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.421       |
|    explained_variance   | -0.0267      |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0185      |
|    n_updates            | 510          |
|    policy_gradient_loss | -0.0132      |
|    value_loss           | 1.03e-05     |
------------------------------------------

------------------------------------------
| time/                   |              |
|    fps                  | 224          |
|    iterations           | 53           |
|    time_elapsed         | 483          |
|    total_timesteps      | 108544       |
| train/                  |              |
|    approx_kl            | 0.0123426225 |
|    clip_fraction        | 0.0881       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.388       |
|    explained_variance   | -0.901       |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0231      |
|    n_updates            | 520          |
|    policy_gradient_loss | -0.0175      |
|    value_loss           | 4.59e-06     |
------------------------------------------

Eval num_timesteps=110000, episode_reward=-1255.38 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.26e+03   |
| time/                   |             |
|    total_timesteps      | 110000      |
| train/                  |             |
|    approx_kl            | 0.011003336 |
|    clip_fraction        | 0.0874      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.393      |
|    explained_variance   | -1.01       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0266     |
|    n_updates            | 530         |
|    policy_gradient_loss | -0.0178     |
|    value_loss           | 5.98e-06    |
-----------------------------------------

New best mean reward!

-------------------------------
| time/              |        |
|    fps             | 214    |
|    iterations      | 54     |
|    time_elapsed    | 516    |
|    total_timesteps | 110592 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 55          |
|    time_elapsed         | 519         |
|    total_timesteps      | 112640      |
| train/                  |             |
|    approx_kl            | 0.008099008 |
|    clip_fraction        | 0.0782      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.401      |
|    explained_variance   | -0.132      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0204     |
|    n_updates            | 540         |
|    policy_gradient_loss | -0.015      |
|    value_loss           | 5.5e-06     |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 56          |
|    time_elapsed         | 523         |
|    total_timesteps      | 114688      |
| train/                  |             |
|    approx_kl            | 0.011305781 |
|    clip_fraction        | 0.097       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.412      |
|    explained_variance   | -0.155      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0333     |
|    n_updates            | 550         |
|    policy_gradient_loss | -0.0163     |
|    value_loss           | 1.03e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 221         |
|    iterations           | 57          |
|    time_elapsed         | 526         |
|    total_timesteps      | 116736      |
| train/                  |             |
|    approx_kl            | 0.008522217 |
|    clip_fraction        | 0.0843      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.407      |
|    explained_variance   | 0.0031      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0108     |
|    n_updates            | 560         |
|    policy_gradient_loss | -0.0146     |
|    value_loss           | 1.03e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 224         |
|    iterations           | 58          |
|    time_elapsed         | 529         |
|    total_timesteps      | 118784      |
| train/                  |             |
|    approx_kl            | 0.011547303 |
|    clip_fraction        | 0.0843      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.402      |
|    explained_variance   | -0.421      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0376     |
|    n_updates            | 570         |
|    policy_gradient_loss | -0.015      |
|    value_loss           | 5.26e-06    |
-----------------------------------------

Eval num_timesteps=120000, episode_reward=-1250.01 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.25e+03   |
| time/                   |             |
|    total_timesteps      | 120000      |
| train/                  |             |
|    approx_kl            | 0.011159759 |
|    clip_fraction        | 0.0897      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.42       |
|    explained_variance   | -0.575      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0249     |
|    n_updates            | 580         |
|    policy_gradient_loss | -0.0151     |
|    value_loss           | 4.38e-06    |
-----------------------------------------

New best mean reward!

-------------------------------
| time/              |        |
|    fps             | 214    |
|    iterations      | 59     |
|    time_elapsed    | 564    |
|    total_timesteps | 120832 |
-------------------------------

---------------------------------------
| time/                   |           |
|    fps                  | 216       |
|    iterations           | 60        |
|    time_elapsed         | 567       |
|    total_timesteps      | 122880    |
| train/                  |           |
|    approx_kl            | 0.0094145 |
|    clip_fraction        | 0.0818    |
|    clip_range           | 0.2       |
|    entropy_loss         | -0.424    |
|    explained_variance   | -0.106    |
|    learning_rate        | 0.0003    |
|    loss                 | -0.029    |
|    n_updates            | 590       |
|    policy_gradient_loss | -0.0168   |
|    value_loss           | 5.04e-06  |
---------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 218         |
|    iterations           | 61          |
|    time_elapsed         | 570         |
|    total_timesteps      | 124928      |
| train/                  |             |
|    approx_kl            | 0.009668584 |
|    clip_fraction        | 0.0954      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.423      |
|    explained_variance   | -0.176      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0415     |
|    n_updates            | 600         |
|    policy_gradient_loss | -0.0161     |
|    value_loss           | 4.34e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 221         |
|    iterations           | 62          |
|    time_elapsed         | 574         |
|    total_timesteps      | 126976      |
| train/                  |             |
|    approx_kl            | 0.011967769 |
|    clip_fraction        | 0.095       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.41       |
|    explained_variance   | -0.427      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0153     |
|    n_updates            | 610         |
|    policy_gradient_loss | -0.0182     |
|    value_loss           | 5.61e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 223         |
|    iterations           | 63          |
|    time_elapsed         | 577         |
|    total_timesteps      | 129024      |
| train/                  |             |
|    approx_kl            | 0.009770592 |
|    clip_fraction        | 0.0966      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.391      |
|    explained_variance   | -0.69       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0141     |
|    n_updates            | 620         |
|    policy_gradient_loss | -0.0181     |
|    value_loss           | 4.45e-06    |
-----------------------------------------

Eval num_timesteps=130000, episode_reward=-1211.18 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.21e+03   |
| time/                   |             |
|    total_timesteps      | 130000      |
| train/                  |             |
|    approx_kl            | 0.008470815 |
|    clip_fraction        | 0.0852      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.403      |
|    explained_variance   | -0.208      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0421     |
|    n_updates            | 630         |
|    policy_gradient_loss | -0.0156     |
|    value_loss           | 7.9e-06     |
-----------------------------------------

New best mean reward!

-------------------------------
| time/              |        |
|    fps             | 214    |
|    iterations      | 64     |
|    time_elapsed    | 611    |
|    total_timesteps | 131072 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 65          |
|    time_elapsed         | 614         |
|    total_timesteps      | 133120      |
| train/                  |             |
|    approx_kl            | 0.009248257 |
|    clip_fraction        | 0.0827      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.402      |
|    explained_variance   | -0.18       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0285     |
|    n_updates            | 640         |
|    policy_gradient_loss | -0.0148     |
|    value_loss           | 5.91e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 218         |
|    iterations           | 66          |
|    time_elapsed         | 617         |
|    total_timesteps      | 135168      |
| train/                  |             |
|    approx_kl            | 0.009084968 |
|    clip_fraction        | 0.0841      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.384      |
|    explained_variance   | 0.0131      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0132     |
|    n_updates            | 650         |
|    policy_gradient_loss | -0.0169     |
|    value_loss           | 3.24e-06    |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 220        |
|    iterations           | 67         |
|    time_elapsed         | 621        |
|    total_timesteps      | 137216     |
| train/                  |            |
|    approx_kl            | 0.00958518 |
|    clip_fraction        | 0.0806     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.372     |
|    explained_variance   | -0.538     |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0162    |
|    n_updates            | 660        |
|    policy_gradient_loss | -0.0168    |
|    value_loss           | 2.77e-06   |
----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 223        |
|    iterations           | 68         |
|    time_elapsed         | 624        |
|    total_timesteps      | 139264     |
| train/                  |            |
|    approx_kl            | 0.00848069 |
|    clip_fraction        | 0.0893     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.378     |
|    explained_variance   | -0.331     |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0233    |
|    n_updates            | 670        |
|    policy_gradient_loss | -0.016     |
|    value_loss           | 4.89e-06   |
----------------------------------------

Eval num_timesteps=140000, episode_reward=-1086.40 +/- 0.00

Episode length: 55832.00 +/- 0.00

------------------------------------------
| eval/                   |              |
|    mean_ep_length       | 5.58e+04     |
|    mean_reward          | -1.09e+03    |
| time/                   |              |
|    total_timesteps      | 140000       |
| train/                  |              |
|    approx_kl            | 0.0112507325 |
|    clip_fraction        | 0.11         |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.391       |
|    explained_variance   | -0.387       |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0569      |
|    n_updates            | 680          |
|    policy_gradient_loss | -0.0193      |
|    value_loss           | 3.34e-06     |
------------------------------------------

New best mean reward!

-------------------------------
| time/              |        |
|    fps             | 214    |
|    iterations      | 69     |
|    time_elapsed    | 657    |
|    total_timesteps | 141312 |
-------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 216        |
|    iterations           | 70         |
|    time_elapsed         | 660        |
|    total_timesteps      | 143360     |
| train/                  |            |
|    approx_kl            | 0.01042427 |
|    clip_fraction        | 0.0783     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.387     |
|    explained_variance   | -0.044     |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0198    |
|    n_updates            | 690        |
|    policy_gradient_loss | -0.0153    |
|    value_loss           | 4.87e-06   |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 218         |
|    iterations           | 71          |
|    time_elapsed         | 664         |
|    total_timesteps      | 145408      |
| train/                  |             |
|    approx_kl            | 0.009574227 |
|    clip_fraction        | 0.0835      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.392      |
|    explained_variance   | -0.213      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0314     |
|    n_updates            | 700         |
|    policy_gradient_loss | -0.017      |
|    value_loss           | 3.76e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 221         |
|    iterations           | 72          |
|    time_elapsed         | 667         |
|    total_timesteps      | 147456      |
| train/                  |             |
|    approx_kl            | 0.007584405 |
|    clip_fraction        | 0.0749      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.386      |
|    explained_variance   | -0.0927     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0114     |
|    n_updates            | 710         |
|    policy_gradient_loss | -0.0125     |
|    value_loss           | 6.43e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 223         |
|    iterations           | 73          |
|    time_elapsed         | 670         |
|    total_timesteps      | 149504      |
| train/                  |             |
|    approx_kl            | 0.008372061 |
|    clip_fraction        | 0.0824      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.37       |
|    explained_variance   | -0.704      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0304     |
|    n_updates            | 720         |
|    policy_gradient_loss | -0.0164     |
|    value_loss           | 3.37e-06    |
-----------------------------------------

Eval num_timesteps=150000, episode_reward=-1100.28 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.1e+03    |
| time/                   |             |
|    total_timesteps      | 150000      |
| train/                  |             |
|    approx_kl            | 0.009575054 |
|    clip_fraction        | 0.0858      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.389      |
|    explained_variance   | -0.0328     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0286     |
|    n_updates            | 730         |
|    policy_gradient_loss | -0.0141     |
|    value_loss           | 5.43e-06    |
-----------------------------------------

-------------------------------
| time/              |        |
|    fps             | 215    |
|    iterations      | 74     |
|    time_elapsed    | 704    |
|    total_timesteps | 151552 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 217         |
|    iterations           | 75          |
|    time_elapsed         | 707         |
|    total_timesteps      | 153600      |
| train/                  |             |
|    approx_kl            | 0.010098381 |
|    clip_fraction        | 0.0914      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.408      |
|    explained_variance   | -0.138      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0396     |
|    n_updates            | 740         |
|    policy_gradient_loss | -0.0163     |
|    value_loss           | 6.57e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 76          |
|    time_elapsed         | 710         |
|    total_timesteps      | 155648      |
| train/                  |             |
|    approx_kl            | 0.010091409 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.401      |
|    explained_variance   | -0.0597     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0357     |
|    n_updates            | 750         |
|    policy_gradient_loss | -0.0149     |
|    value_loss           | 4e-06       |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 220        |
|    iterations           | 77         |
|    time_elapsed         | 714        |
|    total_timesteps      | 157696     |
| train/                  |            |
|    approx_kl            | 0.00973523 |
|    clip_fraction        | 0.0871     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.397     |
|    explained_variance   | -0.142     |
|    learning_rate        | 0.0003     |
|    loss                 | -0.038     |
|    n_updates            | 760        |
|    policy_gradient_loss | -0.0161    |
|    value_loss           | 4.76e-06   |
----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 222        |
|    iterations           | 78         |
|    time_elapsed         | 718        |
|    total_timesteps      | 159744     |
| train/                  |            |
|    approx_kl            | 0.01069651 |
|    clip_fraction        | 0.0909     |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.375     |
|    explained_variance   | -1.01      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0306    |
|    n_updates            | 770        |
|    policy_gradient_loss | -0.0194    |
|    value_loss           | 2.79e-06   |
----------------------------------------

Eval num_timesteps=160000, episode_reward=-976.53 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -977        |
| time/                   |             |
|    total_timesteps      | 160000      |
| train/                  |             |
|    approx_kl            | 0.007976288 |
|    clip_fraction        | 0.0921      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.377      |
|    explained_variance   | -0.187      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0333     |
|    n_updates            | 780         |
|    policy_gradient_loss | -0.0169     |
|    value_loss           | 3.52e-06    |
-----------------------------------------

New best mean reward!

-------------------------------
| time/              |        |
|    fps             | 214    |
|    iterations      | 79     |
|    time_elapsed    | 754    |
|    total_timesteps | 161792 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 80          |
|    time_elapsed         | 757         |
|    total_timesteps      | 163840      |
| train/                  |             |
|    approx_kl            | 0.010039652 |
|    clip_fraction        | 0.0882      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.379      |
|    explained_variance   | -0.0769     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0319     |
|    n_updates            | 790         |
|    policy_gradient_loss | -0.0158     |
|    value_loss           | 5.44e-06    |
-----------------------------------------

------------------------------------------
| time/                   |              |
|    fps                  | 218          |
|    iterations           | 81           |
|    time_elapsed         | 760          |
|    total_timesteps      | 165888       |
| train/                  |              |
|    approx_kl            | 0.0073376703 |
|    clip_fraction        | 0.0744       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.381       |
|    explained_variance   | -0.0462      |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0269      |
|    n_updates            | 800          |
|    policy_gradient_loss | -0.0137      |
|    value_loss           | 6.45e-06     |
------------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 82          |
|    time_elapsed         | 763         |
|    total_timesteps      | 167936      |
| train/                  |             |
|    approx_kl            | 0.007849928 |
|    clip_fraction        | 0.0861      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.379      |
|    explained_variance   | -0.0614     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0213     |
|    n_updates            | 810         |
|    policy_gradient_loss | -0.014      |
|    value_loss           | 6.6e-06     |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 221         |
|    iterations           | 83          |
|    time_elapsed         | 766         |
|    total_timesteps      | 169984      |
| train/                  |             |
|    approx_kl            | 0.012215289 |
|    clip_fraction        | 0.0894      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.377      |
|    explained_variance   | -1.04       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0309     |
|    n_updates            | 820         |
|    policy_gradient_loss | -0.02       |
|    value_loss           | 2.07e-06    |
-----------------------------------------

Eval num_timesteps=170000, episode_reward=-985.76 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -986        |
| time/                   |             |
|    total_timesteps      | 170000      |
| train/                  |             |
|    approx_kl            | 0.011038404 |
|    clip_fraction        | 0.0873      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.402      |
|    explained_variance   | -0.117      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0259     |
|    n_updates            | 830         |
|    policy_gradient_loss | -0.0156     |
|    value_loss           | 6.18e-06    |
-----------------------------------------

-------------------------------
| time/              |        |
|    fps             | 214    |
|    iterations      | 84     |
|    time_elapsed    | 800    |
|    total_timesteps | 172032 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 85          |
|    time_elapsed         | 804         |
|    total_timesteps      | 174080      |
| train/                  |             |
|    approx_kl            | 0.011706017 |
|    clip_fraction        | 0.103       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.401      |
|    explained_variance   | -0.0939     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0398     |
|    n_updates            | 840         |
|    policy_gradient_loss | -0.0181     |
|    value_loss           | 5.81e-06    |
-----------------------------------------

----------------------------------------
| time/                   |            |
|    fps                  | 218        |
|    iterations           | 86         |
|    time_elapsed         | 807        |
|    total_timesteps      | 176128     |
| train/                  |            |
|    approx_kl            | 0.00774531 |
|    clip_fraction        | 0.077      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.373     |
|    explained_variance   | -0.0673    |
|    learning_rate        | 0.0003     |
|    loss                 | -0.033     |
|    n_updates            | 850        |
|    policy_gradient_loss | -0.0162    |
|    value_loss           | 4.26e-06   |
----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 87          |
|    time_elapsed         | 810         |
|    total_timesteps      | 178176      |
| train/                  |             |
|    approx_kl            | 0.009882607 |
|    clip_fraction        | 0.0974      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.39       |
|    explained_variance   | 0.00385     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0299     |
|    n_updates            | 860         |
|    policy_gradient_loss | -0.0156     |
|    value_loss           | 8.15e-06    |
-----------------------------------------

Eval num_timesteps=180000, episode_reward=-1041.99 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.04e+03   |
| time/                   |             |
|    total_timesteps      | 180000      |
| train/                  |             |
|    approx_kl            | 0.008848945 |
|    clip_fraction        | 0.0928      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.372      |
|    explained_variance   | -0.0632     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.017      |
|    n_updates            | 870         |
|    policy_gradient_loss | -0.0138     |
|    value_loss           | 1.05e-05    |
-----------------------------------------

-------------------------------
| time/              |        |
|    fps             | 213    |
|    iterations      | 88     |
|    time_elapsed    | 845    |
|    total_timesteps | 180224 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 214         |
|    iterations           | 89          |
|    time_elapsed         | 848         |
|    total_timesteps      | 182272      |
| train/                  |             |
|    approx_kl            | 0.010515029 |
|    clip_fraction        | 0.0982      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.389      |
|    explained_variance   | 0.0125      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0513     |
|    n_updates            | 880         |
|    policy_gradient_loss | -0.0163     |
|    value_loss           | 1.21e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 90          |
|    time_elapsed         | 851         |
|    total_timesteps      | 184320      |
| train/                  |             |
|    approx_kl            | 0.012429791 |
|    clip_fraction        | 0.108       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.404      |
|    explained_variance   | 0.027       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0172     |
|    n_updates            | 890         |
|    policy_gradient_loss | -0.0175     |
|    value_loss           | 1.09e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 217         |
|    iterations           | 91          |
|    time_elapsed         | 854         |
|    total_timesteps      | 186368      |
| train/                  |             |
|    approx_kl            | 0.009347927 |
|    clip_fraction        | 0.0865      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.384      |
|    explained_variance   | -0.0785     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00887    |
|    n_updates            | 900         |
|    policy_gradient_loss | -0.0168     |
|    value_loss           | 1.71e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 92          |
|    time_elapsed         | 858         |
|    total_timesteps      | 188416      |
| train/                  |             |
|    approx_kl            | 0.011974824 |
|    clip_fraction        | 0.0932      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.397      |
|    explained_variance   | -0.0203     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0203     |
|    n_updates            | 910         |
|    policy_gradient_loss | -0.0133     |
|    value_loss           | 2.58e-05    |
-----------------------------------------

Eval num_timesteps=190000, episode_reward=-1097.32 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.1e+03    |
| time/                   |             |
|    total_timesteps      | 190000      |
| train/                  |             |
|    approx_kl            | 0.007814987 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.389      |
|    explained_variance   | -0.165      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0295     |
|    n_updates            | 920         |
|    policy_gradient_loss | -0.0139     |
|    value_loss           | 7.45e-06    |
-----------------------------------------

-------------------------------
| time/              |        |
|    fps             | 213    |
|    iterations      | 93     |
|    time_elapsed    | 893    |
|    total_timesteps | 190464 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 214         |
|    iterations           | 94          |
|    time_elapsed         | 896         |
|    total_timesteps      | 192512      |
| train/                  |             |
|    approx_kl            | 0.009720612 |
|    clip_fraction        | 0.0845      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.396      |
|    explained_variance   | -0.0862     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0433     |
|    n_updates            | 930         |
|    policy_gradient_loss | -0.0131     |
|    value_loss           | 9.62e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 95          |
|    time_elapsed         | 899         |
|    total_timesteps      | 194560      |
| train/                  |             |
|    approx_kl            | 0.010307506 |
|    clip_fraction        | 0.0994      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.394      |
|    explained_variance   | -0.00809    |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0293     |
|    n_updates            | 940         |
|    policy_gradient_loss | -0.0169     |
|    value_loss           | 6.55e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 217         |
|    iterations           | 96          |
|    time_elapsed         | 903         |
|    total_timesteps      | 196608      |
| train/                  |             |
|    approx_kl            | 0.008103142 |
|    clip_fraction        | 0.0786      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.394      |
|    explained_variance   | -0.0114     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0266     |
|    n_updates            | 950         |
|    policy_gradient_loss | -0.0134     |
|    value_loss           | 1.11e-05    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 219         |
|    iterations           | 97          |
|    time_elapsed         | 906         |
|    total_timesteps      | 198656      |
| train/                  |             |
|    approx_kl            | 0.009131839 |
|    clip_fraction        | 0.085       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.385      |
|    explained_variance   | -0.0383     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0316     |
|    n_updates            | 960         |
|    policy_gradient_loss | -0.0157     |
|    value_loss           | 5.16e-06    |
-----------------------------------------

Eval num_timesteps=200000, episode_reward=-1204.84 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.2e+03    |
| time/                   |             |
|    total_timesteps      | 200000      |
| train/                  |             |
|    approx_kl            | 0.008076221 |
|    clip_fraction        | 0.082       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.385      |
|    explained_variance   | 0.0603      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0357     |
|    n_updates            | 970         |
|    policy_gradient_loss | -0.0157     |
|    value_loss           | 6.38e-06    |
-----------------------------------------

-------------------------------
| time/              |        |
|    fps             | 213    |
|    iterations      | 98     |
|    time_elapsed    | 941    |
|    total_timesteps | 200704 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 214         |
|    iterations           | 99          |
|    time_elapsed         | 944         |
|    total_timesteps      | 202752      |
| train/                  |             |
|    approx_kl            | 0.008285122 |
|    clip_fraction        | 0.0752      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.388      |
|    explained_variance   | -0.00888    |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0356     |
|    n_updates            | 980         |
|    policy_gradient_loss | -0.014      |
|    value_loss           | 7.38e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 215         |
|    iterations           | 100         |
|    time_elapsed         | 948         |
|    total_timesteps      | 204800      |
| train/                  |             |
|    approx_kl            | 0.008998495 |
|    clip_fraction        | 0.0821      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.387      |
|    explained_variance   | 0.0429      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.00221    |
|    n_updates            | 990         |
|    policy_gradient_loss | -0.0137     |
|    value_loss           | 5.87e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 217         |
|    iterations           | 101         |
|    time_elapsed         | 952         |
|    total_timesteps      | 206848      |
| train/                  |             |
|    approx_kl            | 0.012136594 |
|    clip_fraction        | 0.082       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.363      |
|    explained_variance   | 0.0237      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0119     |
|    n_updates            | 1000        |
|    policy_gradient_loss | -0.0146     |
|    value_loss           | 5.84e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 218         |
|    iterations           | 102         |
|    time_elapsed         | 956         |
|    total_timesteps      | 208896      |
| train/                  |             |
|    approx_kl            | 0.009893537 |
|    clip_fraction        | 0.0832      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.383      |
|    explained_variance   | -0.0787     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0201     |
|    n_updates            | 1010        |
|    policy_gradient_loss | -0.0175     |
|    value_loss           | 5.29e-06    |
-----------------------------------------

Eval num_timesteps=210000, episode_reward=-1067.23 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.07e+03   |
| time/                   |             |
|    total_timesteps      | 210000      |
| train/                  |             |
|    approx_kl            | 0.009666491 |
|    clip_fraction        | 0.0866      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.4        |
|    explained_variance   | -0.134      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0462     |
|    n_updates            | 1020        |
|    policy_gradient_loss | -0.0203     |
|    value_loss           | 3.21e-06    |
-----------------------------------------

-------------------------------
| time/              |        |
|    fps             | 212    |
|    iterations      | 103    |
|    time_elapsed    | 991    |
|    total_timesteps | 210944 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 213         |
|    iterations           | 104         |
|    time_elapsed         | 995         |
|    total_timesteps      | 212992      |
| train/                  |             |
|    approx_kl            | 0.008800801 |
|    clip_fraction        | 0.095       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.382      |
|    explained_variance   | 0.0458      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0297     |
|    n_updates            | 1030        |
|    policy_gradient_loss | -0.0182     |
|    value_loss           | 8.52e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 215         |
|    iterations           | 105         |
|    time_elapsed         | 998         |
|    total_timesteps      | 215040      |
| train/                  |             |
|    approx_kl            | 0.008046386 |
|    clip_fraction        | 0.0887      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.383      |
|    explained_variance   | 0.0596      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.000641   |
|    n_updates            | 1040        |
|    policy_gradient_loss | -0.014      |
|    value_loss           | 9.32e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 106         |
|    time_elapsed         | 1001        |
|    total_timesteps      | 217088      |
| train/                  |             |
|    approx_kl            | 0.010848252 |
|    clip_fraction        | 0.104       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.403      |
|    explained_variance   | 0.0354      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.015      |
|    n_updates            | 1050        |
|    policy_gradient_loss | -0.0147     |
|    value_loss           | 9.24e-06    |
-----------------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 217         |
|    iterations           | 107         |
|    time_elapsed         | 1005        |
|    total_timesteps      | 219136      |
| train/                  |             |
|    approx_kl            | 0.007414828 |
|    clip_fraction        | 0.0805      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.38       |
|    explained_variance   | 0.00579     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0273     |
|    n_updates            | 1060        |
|    policy_gradient_loss | -0.0161     |
|    value_loss           | 1.06e-05    |
-----------------------------------------

Eval num_timesteps=220000, episode_reward=-1061.59 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.06e+03   |
| time/                   |             |
|    total_timesteps      | 220000      |
| train/                  |             |
|    approx_kl            | 0.008406572 |
|    clip_fraction        | 0.0807      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.37       |
|    explained_variance   | 0.00878     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0431     |
|    n_updates            | 1070        |
|    policy_gradient_loss | -0.0145     |
|    value_loss           | 1.11e-05    |
-----------------------------------------

-------------------------------
| time/              |        |
|    fps             | 212    |
|    iterations      | 108    |
|    time_elapsed    | 1040   |
|    total_timesteps | 221184 |
-------------------------------

-----------------------------------------
| time/                   |             |
|    fps                  | 213         |
|    iterations           | 109         |
|    time_elapsed         | 1043        |
|    total_timesteps      | 223232      |
| train/                  |             |
|    approx_kl            | 0.008890782 |
|    clip_fraction        | 0.0822      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.373      |
|    explained_variance   | 0.028       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0186     |
|    n_updates            | 1080        |
|    policy_gradient_loss | -0.0135     |
|    value_loss           | 1.43e-05    |
-----------------------------------------

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 2.23e+05     |
|    ep_rew_mean          | -1.1e+04     |
| time/                   |              |
|    fps                  | 215          |
|    iterations           | 110          |
|    time_elapsed         | 1046         |
|    total_timesteps      | 225280       |
| train/                  |              |
|    approx_kl            | 0.0077149607 |
|    clip_fraction        | 0.0818       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.353       |
|    explained_variance   | 0.0582       |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0354      |
|    n_updates            | 1090         |
|    policy_gradient_loss | -0.016       |
|    value_loss           | 1.35e-05     |
------------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 111         |
|    time_elapsed         | 1050        |
|    total_timesteps      | 227328      |
| train/                  |             |
|    approx_kl            | 0.016443407 |
|    clip_fraction        | 0.0979      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.389      |
|    explained_variance   | -0.00012    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.0473      |
|    n_updates            | 1100        |
|    policy_gradient_loss | -0.0123     |
|    value_loss           | 0.105       |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 217         |
|    iterations           | 112         |
|    time_elapsed         | 1053        |
|    total_timesteps      | 229376      |
| train/                  |             |
|    approx_kl            | 0.011920559 |
|    clip_fraction        | 0.0916      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.415      |
|    explained_variance   | -0.395      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.000767   |
|    n_updates            | 1110        |
|    policy_gradient_loss | -0.0192     |
|    value_loss           | 0.0111      |
-----------------------------------------

Eval num_timesteps=230000, episode_reward=-1166.38 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.17e+03   |
| time/                   |             |
|    total_timesteps      | 230000      |
| train/                  |             |
|    approx_kl            | 0.011533177 |
|    clip_fraction        | 0.101       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.433      |
|    explained_variance   | 0.078       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0209     |
|    n_updates            | 1120        |
|    policy_gradient_loss | -0.0199     |
|    value_loss           | 0.00728     |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 2.23e+05 |
|    ep_rew_mean     | -1.1e+04 |
| time/              |          |
|    fps             | 212      |
|    iterations      | 113      |
|    time_elapsed    | 1088     |
|    total_timesteps | 231424   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 213         |
|    iterations           | 114         |
|    time_elapsed         | 1091        |
|    total_timesteps      | 233472      |
| train/                  |             |
|    approx_kl            | 0.009963656 |
|    clip_fraction        | 0.0899      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.439      |
|    explained_variance   | -0.228      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0547     |
|    n_updates            | 1130        |
|    policy_gradient_loss | -0.0204     |
|    value_loss           | 0.00383     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 214         |
|    iterations           | 115         |
|    time_elapsed         | 1095        |
|    total_timesteps      | 235520      |
| train/                  |             |
|    approx_kl            | 0.011097467 |
|    clip_fraction        | 0.105       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.448      |
|    explained_variance   | -0.0346     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0436     |
|    n_updates            | 1140        |
|    policy_gradient_loss | -0.0178     |
|    value_loss           | 0.00222     |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 116         |
|    time_elapsed         | 1099        |
|    total_timesteps      | 237568      |
| train/                  |             |
|    approx_kl            | 0.010915182 |
|    clip_fraction        | 0.0969      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.471      |
|    explained_variance   | 0.13        |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0412     |
|    n_updates            | 1150        |
|    policy_gradient_loss | -0.0239     |
|    value_loss           | 0.000842    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 217         |
|    iterations           | 117         |
|    time_elapsed         | 1102        |
|    total_timesteps      | 239616      |
| train/                  |             |
|    approx_kl            | 0.008550025 |
|    clip_fraction        | 0.0918      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.44       |
|    explained_variance   | -0.042      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0289     |
|    n_updates            | 1160        |
|    policy_gradient_loss | -0.0191     |
|    value_loss           | 0.000309    |
-----------------------------------------

Eval num_timesteps=240000, episode_reward=-1271.56 +/- 0.00

Episode length: 55832.00 +/- 0.00

----------------------------------------
| eval/                   |            |
|    mean_ep_length       | 5.58e+04   |
|    mean_reward          | -1.27e+03  |
| time/                   |            |
|    total_timesteps      | 240000     |
| train/                  |            |
|    approx_kl            | 0.00956699 |
|    clip_fraction        | 0.1        |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.476     |
|    explained_variance   | 0.114      |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0345    |
|    n_updates            | 1170       |
|    policy_gradient_loss | -0.0188    |
|    value_loss           | 0.00024    |
----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 2.23e+05 |
|    ep_rew_mean     | -1.1e+04 |
| time/              |          |
|    fps             | 212      |
|    iterations      | 118      |
|    time_elapsed    | 1138     |
|    total_timesteps | 241664   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 213         |
|    iterations           | 119         |
|    time_elapsed         | 1141        |
|    total_timesteps      | 243712      |
| train/                  |             |
|    approx_kl            | 0.008136276 |
|    clip_fraction        | 0.0889      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.47       |
|    explained_variance   | -0.464      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0281     |
|    n_updates            | 1180        |
|    policy_gradient_loss | -0.0182     |
|    value_loss           | 5.89e-05    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 214         |
|    iterations           | 120         |
|    time_elapsed         | 1145        |
|    total_timesteps      | 245760      |
| train/                  |             |
|    approx_kl            | 0.009383336 |
|    clip_fraction        | 0.0938      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.467      |
|    explained_variance   | 0.0796      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0309     |
|    n_updates            | 1190        |
|    policy_gradient_loss | -0.0196     |
|    value_loss           | 0.000364    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 215         |
|    iterations           | 121         |
|    time_elapsed         | 1148        |
|    total_timesteps      | 247808      |
| train/                  |             |
|    approx_kl            | 0.010022547 |
|    clip_fraction        | 0.0913      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.444      |
|    explained_variance   | -0.0998     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0428     |
|    n_updates            | 1200        |
|    policy_gradient_loss | -0.0194     |
|    value_loss           | 0.000218    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 216         |
|    iterations           | 122         |
|    time_elapsed         | 1152        |
|    total_timesteps      | 249856      |
| train/                  |             |
|    approx_kl            | 0.011330322 |
|    clip_fraction        | 0.106       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.462      |
|    explained_variance   | 0.0577      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0404     |
|    n_updates            | 1210        |
|    policy_gradient_loss | -0.0202     |
|    value_loss           | 0.000414    |
-----------------------------------------

Eval num_timesteps=250000, episode_reward=-1363.19 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.36e+03   |
| time/                   |             |
|    total_timesteps      | 250000      |
| train/                  |             |
|    approx_kl            | 0.011361089 |
|    clip_fraction        | 0.102       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.443      |
|    explained_variance   | -0.108      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0262     |
|    n_updates            | 1220        |
|    policy_gradient_loss | -0.0215     |
|    value_loss           | 0.000324    |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 2.23e+05 |
|    ep_rew_mean     | -1.1e+04 |
| time/              |          |
|    fps             | 212      |
|    iterations      | 123      |
|    time_elapsed    | 1186     |
|    total_timesteps | 251904   |
---------------------------------

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 2.23e+05     |
|    ep_rew_mean          | -1.1e+04     |
| time/                   |              |
|    fps                  | 213          |
|    iterations           | 124          |
|    time_elapsed         | 1190         |
|    total_timesteps      | 253952       |
| train/                  |              |
|    approx_kl            | 0.0122733675 |
|    clip_fraction        | 0.102        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.45        |
|    explained_variance   | -0.0911      |
|    learning_rate        | 0.0003       |
|    loss                 | -0.0409      |
|    n_updates            | 1230         |
|    policy_gradient_loss | -0.019       |
|    value_loss           | 0.00033      |
------------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 214         |
|    iterations           | 125         |
|    time_elapsed         | 1193        |
|    total_timesteps      | 256000      |
| train/                  |             |
|    approx_kl            | 0.010542069 |
|    clip_fraction        | 0.094       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.455      |
|    explained_variance   | 0.0105      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0253     |
|    n_updates            | 1240        |
|    policy_gradient_loss | -0.0189     |
|    value_loss           | 0.000377    |
-----------------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 215         |
|    iterations           | 126         |
|    time_elapsed         | 1197        |
|    total_timesteps      | 258048      |
| train/                  |             |
|    approx_kl            | 0.010960647 |
|    clip_fraction        | 0.0987      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.448      |
|    explained_variance   | -0.175      |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0383     |
|    n_updates            | 1250        |
|    policy_gradient_loss | -0.0226     |
|    value_loss           | 0.00039     |
-----------------------------------------

Eval num_timesteps=260000, episode_reward=-1376.62 +/- 0.00

Episode length: 55832.00 +/- 0.00

-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 5.58e+04    |
|    mean_reward          | -1.38e+03   |
| time/                   |             |
|    total_timesteps      | 260000      |
| train/                  |             |
|    approx_kl            | 0.011324713 |
|    clip_fraction        | 0.0887      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.441      |
|    explained_variance   | -0.0956     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0589     |
|    n_updates            | 1260        |
|    policy_gradient_loss | -0.0193     |
|    value_loss           | 0.000327    |
-----------------------------------------

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 2.23e+05 |
|    ep_rew_mean     | -1.1e+04 |
| time/              |          |
|    fps             | 211      |
|    iterations      | 127      |
|    time_elapsed    | 1231     |
|    total_timesteps | 260096   |
---------------------------------

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 2.23e+05    |
|    ep_rew_mean          | -1.1e+04    |
| time/                   |             |
|    fps                  | 212         |
|    iterations           | 128         |
|    time_elapsed         | 1235        |
|    total_timesteps      | 262144      |
| train/                  |             |
|    approx_kl            | 0.013783487 |
|    clip_fraction        | 0.121       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.423      |
|    explained_variance   | -0.0756     |
|    learning_rate        | 0.0003      |
|    loss                 | -0.034      |
|    n_updates            | 1270        |
|    policy_gradient_loss | -0.0247     |
|    value_loss           | 0.000317    |
-----------------------------------------

----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 2.23e+05   |
|    ep_rew_mean          | -1.1e+04   |
| time/                   |            |
|    fps                  | 213        |
|    iterations           | 129        |
|    time_elapsed         | 1239       |
|    total_timesteps      | 264192     |
| train/                  |            |
|    approx_kl            | 0.01484509 |
|    clip_fraction        | 0.101      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.446     |
|    explained_variance   | -0.0558    |
|    learning_rate        | 0.0003     |
|    loss                 | -0.0344    |
|    n_updates            | 1280       |
|    policy_gradient_loss | -0.0212    |
|    value_loss           | 0.000278   |
----------------------------------------

--------------------------------------
| rollout/                |          |
|    ep_len_mean          | 2.23e+05 |
|    ep_rew_mean          | -1.1e+04 |
| time/                   |          |
|    fps                  | 214      |
|    iterations           | 130      |
|    time_elapsed         | 1243     |
|    total_timesteps      | 266240   |
| train/                  |          |
|    approx_kl            | 0.015928 |
|    clip_fraction        | 0.114    |
|    clip_range           | 0.2      |
|    entropy_loss         | -0.448   |
|    explained_variance   | -0.0238  |
|    learning_rate        | 0.0003   |
|    loss                 | -0.0418  |
|    n_updates            | 1290     |
|    policy_gradient_loss | -0.0246  |
|    value_loss           | 0.000348 |
--------------------------------------

## 6. 回测评估

使用验证集运行确定性策略（`explore=False`），评估以下指标：

| 指标 | 说明 |
|---|---|
| 总收益率 | 最终资产 / 初始资产 − 1 |
| 最大回撤 | max((peak − PV) / peak) |
| 夏普比率 | 步均收益 / 步均波动 × √(365×24×60) |
| 交易次数 | 买入 + 卖出信号总数 |

In [ ]:
# 加载最佳模型（EvalCallback 保存）
best_path = f"{MODEL_DIR}/{RUN_NAME}/best_model"
eval_model = PPO.load(best_path)
print(f"加载模型: {best_path}.zip")

# 确定性回测
eval_env_raw = CryptoPPOEnv(eval_feat, eval_price)
obs, _ = eval_env_raw.reset()
done = False
while not done:
    action, _ = eval_model.predict(obs, deterministic=True)
    obs, reward, done, _, info = eval_env_raw.step(int(action))

pv_curve = np.array(eval_env_raw.portfolio_history)
trades   = eval_env_raw.trades
prices_eval = eval_price[WINDOW_SIZE + 1:]  # 对齐 pv_curve（env 第一步后才写入 pv）

# ── 指标计算 ───────────────────────────────────────────────────
total_return = pv_curve[-1] / INITIAL_BALANCE - 1
peak = np.maximum.accumulate(pv_curve)
drawdowns = (peak - pv_curve) / (peak + 1e-8)
max_dd = drawdowns.max()

step_rets = np.diff(pv_curve) / (pv_curve[:-1] + 1e-8)
sharpe = (step_rets.mean() / (step_rets.std() + 1e-8)) * np.sqrt(365 * 24 * 60)

bh_return = eval_price[-1] / eval_price[WINDOW_SIZE] - 1  # buy-and-hold baseline

print(f"{'═'*40}")
print(f"  验证集回测结果")
print(f"{'═'*40}")
print(f"  总收益率   : {total_return:+.2%}")
print(f"  买入持有   : {bh_return:+.2%}  (baseline)")
print(f"  最大回撤   : {max_dd:.2%}")
print(f"  夏普比率   : {sharpe:.2f}")
print(f"  交易次数   : {len(trades)}")
print(f"{'═'*40}")

In [ ]:
# ── 可视化 ────────────────────────────────────────────────────
fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=False)
fig.suptitle(f"{SYMBOL}  PPO 验证集回测", fontsize=14)

ts_eval = eval_time.iloc[WINDOW_SIZE + 1:].reset_index(drop=True)

# Row 1: 资产曲线 vs 买入持有
bh_curve = INITIAL_BALANCE * (prices_eval / prices_eval[0])
ax0 = axes[0]
ax0.plot(ts_eval, pv_curve, label="PPO 策略", color="#2196f3", linewidth=1.2)
ax0.plot(ts_eval, bh_curve, label="买入持有", color="#ff9800", linewidth=1, linestyle="--", alpha=0.8)
ax0.fill_between(ts_eval, pv_curve, bh_curve,
                 where=pv_curve >= bh_curve, alpha=0.15, color="#4caf50", label="策略超额")
ax0.fill_between(ts_eval, pv_curve, bh_curve,
                 where=pv_curve < bh_curve,  alpha=0.15, color="#ef5350")
ax0.set_ylabel("资产价值 (USD)")
ax0.legend(loc="upper left", fontsize=9)
ax0.grid(True, alpha=0.3)

# 标注买卖点
buy_steps  = [t["step"] - WINDOW_SIZE for t in trades if t["side"] == "buy"  and t["step"] - WINDOW_SIZE < len(ts_eval)]
sell_steps = [t["step"] - WINDOW_SIZE for t in trades if t["side"] == "sell" and t["step"] - WINDOW_SIZE < len(ts_eval)]
if buy_steps:
    ax0.scatter(ts_eval.iloc[buy_steps],  pv_curve[buy_steps],
                color="#4caf50", marker="^", s=40, zorder=5, label="买入")
if sell_steps:
    ax0.scatter(ts_eval.iloc[sell_steps], pv_curve[sell_steps],
                color="#ef5350", marker="v", s=40, zorder=5, label="卖出")
ax0.legend(loc="upper left", fontsize=9)

# Row 2: 回撤曲线
ax1 = axes[1]
ax1.fill_between(ts_eval, drawdowns * 100, alpha=0.6, color="#ef5350")
ax1.axhline(max_dd * 100, color="red", linestyle="--", linewidth=1,
            label=f"最大回撤 {max_dd:.2%}")
ax1.set_ylabel("回撤 (%)")
ax1.invert_yaxis()
ax1.legend(fontsize=9)
ax1.grid(True, alpha=0.3)

# Row 3: 滚动夏普（60步窗口）
roll_w = 60
roll_ret  = pd.Series(step_rets)
roll_sharpe = (roll_ret.rolling(roll_w).mean()
               / (roll_ret.rolling(roll_w).std() + 1e-8)) * np.sqrt(365 * 24 * 60)
ax2 = axes[2]
ax2.plot(ts_eval.iloc[1:], roll_sharpe, color="#ba68c8", linewidth=1)
ax2.axhline(0,   color="white",   linestyle="--", linewidth=0.8, alpha=0.5)
ax2.axhline(1,   color="#4caf50", linestyle="--", linewidth=0.8, alpha=0.7)
ax2.axhline(-1,  color="#ef5350", linestyle="--", linewidth=0.8, alpha=0.7)
ax2.set_ylabel(f"滚动夏普 ({roll_w}步)")
ax2.grid(True, alpha=0.3)

for ax in axes:
    ax.tick_params(axis="x", rotation=30)
plt.tight_layout()
plt.savefig(f"{MODEL_DIR}/{RUN_NAME}_backtest.png", dpi=120, bbox_inches="tight")
plt.show()
print("图表已保存")